version: '3.8'

services:
  apache:
    image: lucaespo95/apache_server:2.4.58  # Immagine personalizzata su Docker Hub
    container_name: apache_server
    ports:
      - "80:80"
    volumes:
      - ./apache/httpd.conf:/Users/lucae/Desktop/hellodocker/httpd.conf
    depends_on:
      - tomcat
    environment:
      TZ: Europe/Rome  # Imposta il fuso orario

  tomcat:
    image: lucaespo95/tomcat_server:9-jdk15-openjdk  # Immagine personalizzata su Docker Hub
    container_name: tomcat_server
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/conf:/usr/local/tomcat/conf
    environment:
      CATALINA_OPTS: -Djava.security.egd=file:/dev/./urandom
      TZ: Europe/Rome  # Imposta il fuso orario

  mariadb:
    image: lucaespo95/mariadb_server:10.4.32  # Immagine personalizzata su Docker Hub
    container_name: mariadb_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Europe/Rome  # Imposta il fuso orario
    volumes:
      - ./mariadb/data:/var/lib/mysql

  phpmyadmin:
    image: lucaespo95/phpmyadmin:latest  # Immagine personalizzata su Docker Hub
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Rome  # Imposta il fuso orario
    depends_on:
      - mariadb



